### ISSUE TITLE
GET api/User by Id returns session_token

### ISSUE THREAD

**Issue by MauriceNino** [gamerpals/Backend#11]
# Expected Behavior
Return only a slice of the data (the non-private data, like description, name, ...), when called without Bearer/Or with a Bearer that does not belong to the user

# Current Behavior
Returns whole user object

# Possible Solution
/

# Detailed Description
GET http://localhost:50606/api/User/id returns session

**Comment by Steffx115** [comment]
Removed current session when not logged in with the correct user -> need to clarify what exactly to remove in this case, only removing current session is only the first step

**Comment by MauriceNino** [comment]
Should be visible by everyone:
- public ObjectId _id { get; set; }
- public DateTime CreateTime { get; set; }
- public string ProfileName { get; set; }
- public string ProfileDescription { get; set; }
- public string ProfilePicture { get; set; }
- public DateTime Birthday { get; set; }
- public ObjectId Country { get; set; }
- public List<ObjectId> Languages { get; set; }
- public string Gender { get; set; }
- public ObjectId Role { get; set; }

Should only be visible by friends:
- public string OnlineStatus { get; set; }
- public List<ObjectId> ActiveSearches { get; set; } 
- public List<ObjectId> PassiveSearches { get; set; }

Should only be visible by yourself:
- public string GoogleId { get; set; }
- public CurrentSession CurrentSession { get; set; }
- public Karma Karma { get; set; }
- public List<ObjectId> GamesSelected { get; set; }
- public List<ObjectId> FriendsList { get; set; }
- public List<RecievedFriendRequest> RecievedFriendRequests { get; set; }
- public List<SentFriendRequest> SentFriendRequests { get; set; }
- public List<ObjectId> PrivateChats { get; set; }
- public List<Notification> Notifications { get; set; }
- public List<ObjectId> ConnectedServices { get; set; }
- public bool ProfileComplete { get; set; }

Thats what I thought. Any problems with it @Steffx115 ?
