### ISSUE TITLE
GET api/Game needs lower permissions

### ISSUE THREAD

**Issue by MauriceNino** [gamerpals/Backend#13]
# Expected Behavior
As a User who has completed his profile, I want to be able to access all games.

# Current Behavior
401 Forbidden

# Possible Solution
/
# Detailed Description
/

**Comment by Steffx115** [comment]
GET methods of /Game are now able to be accessed by verified Users

**Comment by MauriceNino** [comment]
Now getting an error 403: Forbidden, with a Bearer that belongs to a user that has profileCompleted: true.
